const SESSION_ID = "SADIYA-MD=DgxiHSwb#BzHzFEmCu_z4cWTKsYGofXeH3z9TS3gW4-BhsKB7CuU"
const GITHUB_USER_NAME = "Queen-Nethu-MDV"
const GITHUB_AUTH_TOKEN = "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"
const DATABASE_REPO_NAME = "SADIYA-MD-DATABASE"

module.exports = {SESSION_ID,GITHUB_USER_NAME,GITHUB_AUTH_TOKEN,DATABASE_REPO_NAME}
